export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const CATEGORY_FETCH_ERROR = "CATEGORY_FETCH_ERROR";

export const SEARCH_FILTER = "SEARCH_FILTER";